import type { ProviderConfig } from '../types/provider.js';

export const PROVIDERS: Record<string, ProviderConfig> = {
  openai: {
    id: 'openai',
    name: 'OpenAI',
    type: 'cloud',
    apiKeyRequired: true,
    baseUrlConfigurable: false,
    defaultBaseUrl: 'https://api.openai.com/v1',
  },
  anthropic: {
    id: 'anthropic',
    name: 'Anthropic',
    type: 'cloud',
    apiKeyRequired: true,
    baseUrlConfigurable: false,
    defaultBaseUrl: 'https://api.anthropic.com',
  },
  google: {
    id: 'google',
    name: 'Google (Gemini)',
    type: 'cloud',
    apiKeyRequired: true,
    baseUrlConfigurable: false,
  },
  ollama: {
    id: 'ollama',
    name: 'Ollama (Local)',
    type: 'local',
    apiKeyRequired: false,
    baseUrlConfigurable: true,
    defaultBaseUrl: 'http://localhost:11434',
  },
  lmstudio: {
    id: 'lmstudio',
    name: 'LM Studio (Local)',
    type: 'local',
    apiKeyRequired: false,
    baseUrlConfigurable: true,
    defaultBaseUrl: 'http://localhost:1234/v1',
  },
  moonshot: {
    id: 'moonshot',
    name: 'Moonshot AI',
    type: 'cloud',
    apiKeyRequired: true,
    baseUrlConfigurable: true,
    defaultBaseUrl: 'https://api.moonshot.cn/v1',
  },
  deepseek: {
    id: 'deepseek',
    name: 'DeepSeek',
    type: 'cloud',
    apiKeyRequired: true,
    baseUrlConfigurable: true,
    defaultBaseUrl: 'https://api.deepseek.com',
  },
  groq: {
    id: 'groq',
    name: 'Groq',
    type: 'cloud',
    apiKeyRequired: true,
    baseUrlConfigurable: true,
    defaultBaseUrl: 'https://api.groq.com/openai/v1',
  },
  mistral: {
    id: 'mistral',
    name: 'Mistral AI',
    type: 'cloud',
    apiKeyRequired: true,
    baseUrlConfigurable: true,
    defaultBaseUrl: 'https://api.mistral.ai/v1',
  },
  together: {
    id: 'together',
    name: 'Together AI',
    type: 'cloud',
    apiKeyRequired: true,
    baseUrlConfigurable: true,
    defaultBaseUrl: 'https://api.together.xyz/v1',
  },
  xai: {
    id: 'xai',
    name: 'xAI (Grok)',
    type: 'cloud',
    apiKeyRequired: true,
    baseUrlConfigurable: true,
    defaultBaseUrl: 'https://api.x.ai/v1',
  },
  fireworks: {
    id: 'fireworks',
    name: 'Fireworks AI',
    type: 'cloud',
    apiKeyRequired: true,
    baseUrlConfigurable: true,
    defaultBaseUrl: 'https://api.fireworks.ai/inference/v1',
  },
  perplexity: {
    id: 'perplexity',
    name: 'Perplexity',
    type: 'cloud',
    apiKeyRequired: true,
    baseUrlConfigurable: true,
    defaultBaseUrl: 'https://api.perplexity.ai',
  },
  azure: {
    id: 'azure',
    name: 'Azure OpenAI',
    type: 'cloud',
    apiKeyRequired: true,
    baseUrlConfigurable: true,
    defaultBaseUrl: '',
  },
  cohere: {
    id: 'cohere',
    name: 'Cohere',
    type: 'cloud',
    apiKeyRequired: true,
    baseUrlConfigurable: true,
    defaultBaseUrl: 'https://api.cohere.com/compatibility/v1',
  },
} as const;

export const PROVIDER_IDS = Object.keys(PROVIDERS) as string[];
