export type { CommandInterface, CommandContext, CommandResult } from './CommandInterface.js';
export { CommandParser } from './CommandParser.js';
export { CommandRegistry } from './CommandRegistry.js';
export { UserCommandRegistry } from './UserCommandRegistry.js';
export type { UserCommandConfig } from './UserCommandRegistry.js';

// Built-in commands
export { helpCommand } from './builtin/help.js';
export { exitCommand } from './builtin/exit.js';
export { clearCommand } from './builtin/clear.js';
export { versionCommand } from './builtin/version.js';
export { modelCommand } from './builtin/model.js';
export { providerCommand } from './builtin/provider.js';
export { crewCommand } from './builtin/crew.js';
export { bgCommand, tasksCommand } from './builtin/tasks.js';
export { toolsCommand, setToolRegistryInstance } from './builtin/tools.js';
export { permissionsCommand } from './builtin/permissions.js';
export { sessionsCommand } from './builtin/sessions.js';
export { rememberCommand } from './builtin/remember.js';
export { telegramCommand } from './builtin/telegram.js';
export { forkCommand } from './builtin/fork.js';
export { exportCommand } from './builtin/export.js';
export { checkpointCommand, rewindCommand } from './builtin/checkpoint.js';
export { costCommand } from './builtin/cost.js';
export { watchCommand } from './builtin/watch.js';
export { routeCommand } from './builtin/route.js';
export { commandsCommand } from './builtin/commands.js';
export { themeCommand } from './builtin/theme_cmd.js';
export { diffCommand } from './builtin/diff_cmd.js';
export { searchCommand } from './builtin/search_cmd.js';
export { ragIndexCommand } from './builtin/rag_index.js';
export { agentsCommand } from './builtin/agents.js';
export { recipeCommand } from './builtin/recipe.js';
export { copyCommand } from './builtin/copy.js';
export { voiceCommand } from './builtin/voice.js';
export { researchCommand } from './builtin/research.js';
export { focusCommand } from './builtin/focus.js';

import { CommandRegistry } from './CommandRegistry.js';
import { helpCommand } from './builtin/help.js';
import { exitCommand } from './builtin/exit.js';
import { clearCommand } from './builtin/clear.js';
import { versionCommand } from './builtin/version.js';
import { modelCommand } from './builtin/model.js';
import { providerCommand } from './builtin/provider.js';
import { crewCommand } from './builtin/crew.js';
import { bgCommand, tasksCommand } from './builtin/tasks.js';
import { toolsCommand } from './builtin/tools.js';
import { permissionsCommand } from './builtin/permissions.js';
import { sessionsCommand } from './builtin/sessions.js';
import { rememberCommand } from './builtin/remember.js';
import { telegramCommand } from './builtin/telegram.js';
import { forkCommand } from './builtin/fork.js';
import { exportCommand } from './builtin/export.js';
import { checkpointCommand, rewindCommand } from './builtin/checkpoint.js';
import { costCommand } from './builtin/cost.js';
import { watchCommand } from './builtin/watch.js';
import { routeCommand } from './builtin/route.js';
import { commandsCommand } from './builtin/commands.js';
import { themeCommand } from './builtin/theme_cmd.js';
import { diffCommand } from './builtin/diff_cmd.js';
import { searchCommand } from './builtin/search_cmd.js';
import { ragIndexCommand } from './builtin/rag_index.js';
import { agentsCommand } from './builtin/agents.js';
import { recipeCommand } from './builtin/recipe.js';
import { copyCommand } from './builtin/copy.js';
import { voiceCommand } from './builtin/voice.js';
import { researchCommand } from './builtin/research.js';
import { focusCommand } from './builtin/focus.js';

export function createDefaultRegistry(): CommandRegistry {
  const registry = new CommandRegistry();
  registry.register(helpCommand);
  registry.register(exitCommand);
  registry.register(clearCommand);
  registry.register(versionCommand);
  registry.register(modelCommand);
  registry.register(providerCommand);
  registry.register(crewCommand);
  registry.register(bgCommand);
  registry.register(tasksCommand);
  registry.register(toolsCommand);
  registry.register(permissionsCommand);
  registry.register(sessionsCommand);
  registry.register(rememberCommand);
  registry.register(telegramCommand);
  registry.register(forkCommand);
  registry.register(exportCommand);
  registry.register(checkpointCommand);
  registry.register(rewindCommand);
  registry.register(costCommand);
  registry.register(watchCommand);
  registry.register(routeCommand);
  registry.register(commandsCommand);
  registry.register(themeCommand);
  registry.register(diffCommand);
  registry.register(searchCommand);
  registry.register(ragIndexCommand);
  registry.register(agentsCommand);
  registry.register(recipeCommand);
  registry.register(copyCommand);
  registry.register(voiceCommand);
  registry.register(researchCommand);
  registry.register(focusCommand);
  return registry;
}
