import { candidateRemote, candidateStdio, field } from './helpers.js';
import { COMMUNICATION_CANDIDATES } from './categories/communication-candidates.js';

/** Evaluation candidates with a verified npm package or public remote MCP endpoint. */
export const CATALOG_CANDIDATES = [
  candidateStdio({
    id: 'supabase',
    name: 'Supabase',
    category: 'dev_ops',
    pkg: '@supabase/mcp-server-supabase',
    description: 'Supabase projects, tables, and SQL (read-only mode recommended).',
    icon: 'database',
    website: 'https://supabase.com',
    envKey: 'SUPABASE_ACCESS_TOKEN',
    envLabel: 'Supabase Access Token',
    extraArgs: ['--read-only'],
    trust: 'verified',
  }),
  candidateRemote({
    id: 'atlassian',
    name: 'Atlassian (Jira & Confluence)',
    category: 'productivity',
    url: 'https://mcp.atlassian.com/v1/mcp/authv2',
    description: 'Jira issues, sprints, and Confluence pages via official remote MCP.',
    icon: 'jira',
    website: 'https://atlassian.com',
    trust: 'official',
    authPrimary: 'oauth',
    evaluationNotes: 'Official Atlassian Rovo MCP - browser OAuth via authv2 endpoint.',
  }),
  candidateStdio({
    id: 'monday',
    name: 'Monday.com',
    category: 'productivity',
    pkg: '@mondaydotcomorg/monday-api-mcp',
    description: 'Boards, items, and updates on Monday.com.',
    icon: 'monday',
    website: 'https://monday.com',
    envKey: 'MONDAY_API_TOKEN',
    envLabel: 'Monday API Token',
  }),
  candidateStdio({
    id: 'clickup',
    name: 'ClickUp',
    category: 'productivity',
    pkg: 'clickup-mcp',
    description: 'Tasks, lists, and spaces in ClickUp.',
    icon: 'clickup',
    website: 'https://clickup.com',
    envKey: 'CLICKUP_API_TOKEN',
    envLabel: 'ClickUp API Token',
  }),
  candidateStdio({
    id: 'trello',
    name: 'Trello',
    category: 'productivity',
    pkg: 'mcp-server-trello',
    description: 'Boards, cards, and lists in Trello.',
    icon: 'trello',
    website: 'https://trello.com',
    envKey: 'TRELLO_API_KEY',
    envLabel: 'Trello API Key',
    fields: [
      field('TRELLO_API_KEY', 'Trello API Key', 'From trello.com/power-ups/admin'),
      field('TRELLO_TOKEN', 'Trello Token', 'Generate via the token link next to your API key'),
    ],
  }),
  candidateStdio({
    id: 'obsidian',
    name: 'Obsidian',
    category: 'productivity',
    pkg: 'obsidian-mcp',
    description: 'Read and search Obsidian vault notes.',
    icon: 'notes',
    website: 'https://obsidian.md',
    authPrimary: 'none',
    evaluationNotes: 'Often requires local Obsidian plugin + vault path configuration.',
  }),
  ...COMMUNICATION_CANDIDATES,
  candidateRemote({
    id: '1stay',
    name: '1Stay Hotels',
    category: 'travel',
    url: 'https://mcp.stayker.com/mcp',
    description: 'Hotel search and real bookings with checkout handoff (300K+ properties).',
    icon: 'hotel',
    website: 'https://1stay.ai',
    trust: 'verified',
    transact: true,
    evaluationNotes: 'Supports search_hotels, book_hotel with secure checkout URL.',
  }),
  candidateStdio({
    id: 'travelcode',
    name: 'TravelCode',
    category: 'travel',
    pkg: 'mcp-travelcode',
    description: 'Flights, hotels, orders, and flight status via TravelCode API.',
    icon: 'flight',
    website: 'https://travel-code.com',
    authPrimary: 'oauth',
    transact: true,
    evaluationNotes: 'Run npx mcp-travelcode-auth auth before connecting.',
  }),
  candidateStdio({
    id: 'booking-com',
    name: 'Booking.com',
    category: 'travel',
    pkg: '@striderlabs/mcp-booking',
    description: 'Search hotels, check availability, and manage reservations on Booking.com.',
    icon: 'hotel',
    website: 'https://booking.com',
    trust: 'community',
    authPrimary: 'none',
    transact: true,
    evaluationNotes: 'Community browser-automation server. Sign in from MCP Store after connecting. The Claude-only official connector has no public MCP URL.',
    connectGuide: [
      { title: 'Connect', body: 'Click Connect to start the local MCP server; no API keys required.' },
      { title: 'Sign in to Booking.com', body: 'After connecting, use Sign in on the provider card in MCP Store. A browser window opens for one-time sign-in; sessions persist locally.' },
    ],
    packageSignIn: {
      loginTool: 'booking_login',
      statusTool: 'booking_status',
      progressTool: 'booking_login_status',
      label: 'Booking.com',
    },
    tools: {
      autoExecute: ['booking_search', 'booking_status', 'booking_login_status'],
    },
  }),
  candidateStdio({
    id: 'quickbooks',
    name: 'QuickBooks',
    category: 'finance',
    pkg: 'quickbooks-mcp',
    description: 'Invoices, expenses, and accounting data from QuickBooks.',
    icon: 'accounting',
    website: 'https://quickbooks.intuit.com',
    authPrimary: 'oauth',
  }),
  candidateStdio({
    id: 'xero',
    name: 'Xero',
    category: 'finance',
    pkg: 'xero-mcp',
    description: 'Accounting, invoices, and contacts in Xero.',
    icon: 'accounting',
    website: 'https://xero.com',
    authPrimary: 'oauth',
  }),
  candidateStdio({
    id: 'coinbase',
    name: 'Coinbase',
    category: 'finance',
    pkg: '@codespar/mcp-coinbase-cdp',
    description: 'Coinbase Developer Platform trading, wallets, and payments.',
    icon: 'crypto',
    website: 'https://coinbase.com',
    fields: [
      field('COINBASE_CDP_KEY_NAME', 'Coinbase CDP key name', 'organizations/<org>/apiKeys/<id>', false),
      field('COINBASE_CDP_PRIVATE_KEY', 'Coinbase CDP private key', '-----BEGIN EC PRIVATE KEY-----...'),
    ],
    transact: true,
  }),
  candidateStdio({
    id: 'yahoo-finance',
    name: 'Yahoo Finance',
    category: 'finance',
    pkg: 'yahoo-finance-mcp',
    description: 'Stock quotes, history, and market summaries.',
    icon: 'chart',
    website: 'https://finance.yahoo.com',
    authPrimary: 'none',
  }),
  candidateStdio({
    id: 'alpha-vantage',
    name: 'Alpha Vantage',
    category: 'finance',
    pkg: 'alpha-vantage-mcp',
    description: 'Market data, forex, and crypto via Alpha Vantage.',
    icon: 'chart',
    website: 'https://alphavantage.co',
    envKey: 'ALPHA_VANTAGE_API_KEY',
    envLabel: 'Alpha Vantage API Key',
  }),
  candidateStdio({
    id: 'amazon',
    name: 'Amazon Seller',
    category: 'shopping',
    pkg: 'amazon-mcp',
    description: 'Product catalog and orders via Amazon SP-API.',
    icon: 'store',
    website: 'https://sellercentral.amazon.com',
    envKey: 'AMAZON_SP_API_REFRESH_TOKEN',
    envLabel: 'SP-API Refresh Token',
    transact: true,
  }),
  candidateStdio({
    id: 'ebay',
    name: 'eBay',
    category: 'shopping',
    pkg: 'ebay-mcp',
    description: 'Listings, orders, and inventory on eBay.',
    icon: 'store',
    website: 'https://ebay.com',
    authPrimary: 'oauth',
  }),
  candidateStdio({
    id: 'woocommerce',
    name: 'WooCommerce',
    category: 'shopping',
    pkg: '@amitgurbani/mcp-server-woocommerce',
    description: 'Products and orders from WooCommerce stores.',
    icon: 'store',
    website: 'https://woocommerce.com',
    envKey: 'WOOCOMMERCE_API_KEY',
    envLabel: 'WooCommerce REST API Key',
  }),
  candidateStdio({
    id: 'walmart',
    name: 'Walmart Marketplace',
    category: 'shopping',
    pkg: 'walmart-mcp',
    description: 'Marketplace items and orders via Walmart APIs.',
    icon: 'store',
    website: 'https://marketplace.walmart.com',
    envKey: 'WALMART_CLIENT_ID',
    envLabel: 'Walmart Client ID',
  }),
  candidateStdio({
    id: 'target',
    name: 'Target',
    category: 'shopping',
    pkg: '@striderlabs/mcp-target',
    description: 'Target product search, cart, and order helpers.',
    icon: 'store',
    website: 'https://target.com',
    authPrimary: 'none',
    transact: true,
  }),
  candidateStdio({
    id: 'mqtt',
    name: 'MQTT',
    category: 'smart_home',
    pkg: 'mqtt-mcp',
    description: 'Publish/subscribe to MQTT topics for IoT devices.',
    icon: 'hub',
    envKey: 'MQTT_BROKER_URL',
    envLabel: 'MQTT Broker URL',
    transact: true,
  }),
];
