import type { IntegrationProvider } from '@agentx/shared';
import { field } from './helpers.js';

/** Production-shipped providers (visible by default in Integrations Hub). */
export const SHIPPED_PROVIDERS: IntegrationProvider[] = [
  {
    id: 'github',
    name: 'GitHub',
    category: 'dev_ops',
    catalogStatus: 'active',
    description: 'Repos, issues, pull requests, and code search via GitHub.',
    icon: 'github',
    website: 'https://github.com',
    trust: 'verified',
    server: {
      type: 'stdio',
      command: 'npx',
      args: ['-y', '@modelcontextprotocol/server-github'],
      package: '@modelcontextprotocol/server-github',
    },
    auth: {
      primary: 'api_key_form',
      developer: ['stdio', 'env'],
      fields: [field('GITHUB_PERSONAL_ACCESS_TOKEN', 'GitHub Personal Access Token', 'ghp_...')],
      connectGuide: [
        { title: 'Create a token', body: 'Open GitHub Settings → Developer settings → Personal access tokens and create a classic token with repo scope.' },
        { title: 'Paste below', body: 'Paste the token in the form. It is stored encrypted on this device only.' },
      ],
    },
    capabilities: { search: true, read: true, write: true, transact: false },
  },
  {
    id: 'notion',
    name: 'Notion',
    category: 'productivity',
    catalogStatus: 'active',
    description: 'Pages, databases, and workspace search in Notion.',
    icon: 'notion',
    website: 'https://notion.so',
    trust: 'verified',
    server: {
      type: 'remote',
      url: 'https://mcp.notion.com/mcp',
      package: 'https://mcp.notion.com/mcp',
    },
    auth: {
      primary: 'oauth',
      developer: ['remote_url', 'oauth'],
      oauth: {
        resource: 'https://mcp.notion.com/mcp',
        scopes: ['mcp'],
      },
      connectGuide: [
        { title: 'Sign in', body: 'Authorize Agent-X with Notion in the browser.' },
        { title: 'Share pages', body: 'Share the pages or databases you want Agent-X to access in Notion.' },
      ],
    },
    capabilities: { search: true, read: true, write: true, transact: false },
  },
  {
    id: 'linear',
    name: 'Linear',
    category: 'productivity',
    catalogStatus: 'active',
    description: 'Issues, projects, and teams in Linear.',
    icon: 'linear',
    website: 'https://linear.app',
    trust: 'verified',
    server: {
      type: 'remote',
      url: 'https://mcp.linear.app/mcp',
      package: 'https://mcp.linear.app/mcp',
    },
    auth: {
      primary: 'oauth',
      developer: ['remote_url', 'oauth'],
      oauth: {
        resource: 'https://mcp.linear.app/mcp',
        scopes: ['mcp'],
      },
    },
    capabilities: { search: true, read: true, write: true, transact: false },
  },
  {
    id: 'gmail',
    name: 'Gmail',
    category: 'communication',
    catalogStatus: 'active',
    description: 'Read, search, and send email from Gmail.',
    icon: 'mail',
    website: 'https://mail.google.com',
    trust: 'community',
    server: {
      type: 'stdio',
      command: 'npx',
      args: ['-y', '@gongrzhe/server-gmail-autoauth-mcp'],
      package: '@gongrzhe/server-gmail-autoauth-mcp',
    },
    auth: {
      primary: 'env',
      developer: ['stdio', 'env'],
      fields: [
        { key: 'GOOGLE_OAUTH_CLIENT_ID', label: 'OAuth Client ID', placeholder: 'xxx.apps.googleusercontent.com', required: true },
        { key: 'GOOGLE_OAUTH_CLIENT_SECRET', label: 'OAuth Client Secret', secret: true, required: true },
      ],
      mcpStdioAuth: {
        authArg: 'auth',
        oauthPathEnv: 'GMAIL_OAUTH_PATH',
        credentialsPathEnv: 'GMAIL_CREDENTIALS_PATH',
        credentialsFileName: 'credentials.json',
        oauthKeysFormat: 'web',
        redirectPath: '/oauth2callback',
        clientIdField: 'GOOGLE_OAUTH_CLIENT_ID',
        clientSecretField: 'GOOGLE_OAUTH_CLIENT_SECRET',
        clientIdEnv: 'AGENTX_GOOGLE_OAUTH_CLIENT_ID',
        clientSecretEnv: 'AGENTX_GOOGLE_OAUTH_CLIENT_SECRET',
        scopes: [
          'https://www.googleapis.com/auth/gmail.modify',
          'https://www.googleapis.com/auth/gmail.settings.basic',
        ],
      },
      connectGuide: [
        { title: 'Enable Gmail API', body: 'In Google Cloud Console enable the Gmail API for your project.', link: 'https://console.cloud.google.com/apis/library/gmail.googleapis.com' },
        { title: 'OAuth consent screen', body: 'Configure the OAuth consent screen. If the app is in Testing mode, add your Google account under Test users — otherwise Google returns Error 403: access_denied. Under Data access, add scopes gmail.modify and gmail.settings.basic.', link: 'https://console.cloud.google.com/apis/credentials/consent' },
        { title: 'Create a Web OAuth client', body: 'Create an OAuth client ID with application type Web application (not Desktop). Under Authorized redirect URIs add your Agent-X callback URL — shown on the sign-in step (default http://localhost:3333/oauth2callback).', link: 'https://console.cloud.google.com/apis/credentials/oauthclient' },
        { title: 'Sign in', body: 'After saving credentials, click Sign in — a browser window opens for one-time Gmail authorization.' },
      ],
    },
    capabilities: { search: true, read: true, write: true, transact: false },
    tools: { alwaysConfirm: ['send', 'reply', 'delete'] },
  },
  {
    id: 'brave-search',
    name: 'Brave Search',
    category: 'dev_ops',
    catalogStatus: 'active',
    description: 'Live web search through the Brave Search API.',
    icon: 'search',
    website: 'https://brave.com/search/api',
    trust: 'verified',
    server: {
      type: 'stdio',
      command: 'npx',
      args: ['-y', '@modelcontextprotocol/server-brave-search'],
      package: '@modelcontextprotocol/server-brave-search',
    },
    auth: {
      primary: 'api_key_form',
      developer: ['stdio', 'env'],
      fields: [field('BRAVE_API_KEY', 'Brave API Key', 'BSA...')],
    },
    capabilities: { search: true, read: true, write: false, transact: false },
  },
  {
    id: 'postgres',
    name: 'PostgreSQL',
    category: 'dev_ops',
    catalogStatus: 'active',
    description: 'Query and inspect PostgreSQL databases.',
    icon: 'database',
    trust: 'verified',
    server: {
      type: 'stdio',
      command: 'npx',
      args: ['-y', '@modelcontextprotocol/server-postgres'],
      package: '@modelcontextprotocol/server-postgres',
    },
    auth: {
      primary: 'api_key_form',
      developer: ['stdio', 'env'],
      fields: [field('DATABASE_URL', 'PostgreSQL connection URL', 'postgresql://user:pass@host/db', false)],
    },
    capabilities: { search: true, read: true, write: false, transact: false },
  },
  {
    id: 'fetch',
    name: 'Fetch',
    category: 'dev_ops',
    catalogStatus: 'active',
    description: 'Fetch URLs and retrieve web content through MCP.',
    icon: 'web',
    trust: 'verified',
    server: {
      type: 'stdio',
      command: 'npx',
      args: ['-y', '@pulsemcp/pulse-fetch'],
      package: '@pulsemcp/pulse-fetch',
    },
    auth: {
      primary: 'none',
      developer: ['stdio'],
    },
    setupWizard: {
      template: 'stdio_none',
      preflight: ['node_available', 'npx_available', 'network_reachable'],
      hideDeveloperTab: true,
    },
    capabilities: { search: false, read: true, write: false, transact: false },
  },
  {
    id: 'filesystem',
    name: 'Filesystem',
    category: 'dev_ops',
    catalogStatus: 'active',
    description: 'Read and write files in an approved directory via MCP.',
    icon: 'folder',
    trust: 'community',
    server: {
      type: 'stdio',
      command: 'npx',
      args: ['-y', '@modelcontextprotocol/server-filesystem', '${HOME}'],
      package: '@modelcontextprotocol/server-filesystem',
    },
    auth: {
      primary: 'none',
      developer: ['stdio'],
      connectGuide: [
        { title: 'Choose a folder', body: 'In Developer options, set the allowed directory path as the last argument to the MCP server command.' },
      ],
    },
    capabilities: { search: true, read: true, write: true, transact: false },
  },
  {
    id: 'custom',
    name: 'Custom MCP Server',
    category: 'custom',
    catalogStatus: 'active',
    description: 'Connect any MCP server by command or remote URL.',
    icon: 'hub',
    trust: 'community',
    server: { type: 'stdio', command: 'npx', args: [] },
    auth: {
      primary: 'remote_url',
      developer: ['stdio', 'env', 'remote_url', 'import_config'],
      connectGuide: [
        { title: 'Remote MCP (recommended)', body: 'Enter your remote MCP URL. Agent-X discovers OAuth automatically when the server requires sign-in.' },
        { title: 'Local stdio', body: 'Use the Developer tab to run a local MCP server via npx or a custom command.' },
      ],
      oauth: {
        scopes: ['mcp'],
      },
    },
    capabilities: { search: true, read: true, write: true, transact: true },
  },
  {
    id: 'google-drive',
    name: 'Google Drive',
    category: 'productivity',
    catalogStatus: 'active',
    description: 'Search, read, and manage files in Google Drive.',
    icon: 'drive',
    website: 'https://drive.google.com',
    trust: 'verified',
    server: {
      type: 'stdio',
      command: 'npx',
      args: ['-y', '@modelcontextprotocol/server-gdrive'],
      package: '@modelcontextprotocol/server-gdrive',
    },
    auth: {
      primary: 'env',
      developer: ['stdio', 'env'],
      fields: [
        { key: 'GOOGLE_OAUTH_CLIENT_ID', label: 'OAuth Client ID', placeholder: 'xxx.apps.googleusercontent.com', required: true },
        { key: 'GOOGLE_OAUTH_CLIENT_SECRET', label: 'OAuth Client Secret', secret: true, required: true },
      ],
      mcpStdioAuth: {
        authArg: 'auth',
        oauthPathEnv: 'GDRIVE_OAUTH_PATH',
        credentialsPathEnv: 'GDRIVE_CREDENTIALS_PATH',
        clientIdField: 'GOOGLE_OAUTH_CLIENT_ID',
        clientSecretField: 'GOOGLE_OAUTH_CLIENT_SECRET',
        clientIdEnv: 'AGENTX_GOOGLE_OAUTH_CLIENT_ID',
        clientSecretEnv: 'AGENTX_GOOGLE_OAUTH_CLIENT_SECRET',
      },
      connectGuide: [
        { title: 'Enable Google Drive API', body: 'In Google Cloud Console enable the Google Drive API for your project.', link: 'https://console.cloud.google.com/apis/library/drive.googleapis.com' },
        { title: 'OAuth consent screen', body: 'Configure the OAuth consent screen. If the app is in Testing mode, add your Google account under Test users — otherwise Google returns Error 403: access_denied.', link: 'https://console.cloud.google.com/apis/credentials/consent' },
        { title: 'Create a Desktop OAuth client', body: 'Create an OAuth client ID with application type Desktop app (not Web). Download is optional — paste the Client ID and Client Secret below.', link: 'https://console.cloud.google.com/apis/credentials/oauthclient' },
        { title: 'Sign in', body: 'After saving credentials, Agent-X runs the Google Drive MCP auth flow in your browser. No redirect URI registration is needed for Desktop clients.' },
      ],
    },
    capabilities: { search: true, read: true, write: true, transact: false },
  },
  {
    id: 'google-maps',
    name: 'Google Maps',
    category: 'travel',
    catalogStatus: 'active',
    description: 'Places, directions, and travel search via Google Maps.',
    icon: 'map',
    website: 'https://maps.google.com',
    trust: 'verified',
    server: {
      type: 'stdio',
      command: 'npx',
      args: ['-y', '@modelcontextprotocol/server-google-maps'],
      package: '@modelcontextprotocol/server-google-maps',
    },
    auth: {
      primary: 'api_key_form',
      developer: ['stdio', 'env'],
      fields: [field('GOOGLE_MAPS_API_KEY', 'Google Maps API Key', 'AIza...', false)],
    },
    capabilities: { search: true, read: true, write: false, transact: false },
  },
  {
    id: 'redis',
    name: 'Redis',
    category: 'dev_ops',
    catalogStatus: 'active',
    description: 'Inspect keys and run read-only Redis commands.',
    icon: 'database',
    trust: 'verified',
    server: {
      type: 'stdio',
      command: 'npx',
      args: ['-y', '@modelcontextprotocol/server-redis'],
      package: '@modelcontextprotocol/server-redis',
    },
    auth: {
      primary: 'api_key_form',
      developer: ['stdio', 'env'],
      fields: [field('REDIS_URL', 'Redis URL', 'redis://localhost:6379', false)],
    },
    capabilities: { search: true, read: true, write: false, transact: false },
  },
  {
    id: 'sqlite',
    name: 'SQLite',
    category: 'dev_ops',
    catalogStatus: 'active',
    description: 'Query local SQLite databases through MCP.',
    icon: 'database',
    trust: 'verified',
    server: {
      type: 'stdio',
      command: 'npx',
      args: ['-y', 'sqlite-mcp-server'],
      package: 'sqlite-mcp-server',
    },
    auth: {
      primary: 'api_key_form',
      developer: ['stdio', 'env'],
      fields: [field('SQLITE_DB_PATH', 'Database file path', '/path/to/db.sqlite', false)],
    },
    capabilities: { search: true, read: true, write: false, transact: false },
  },
  {
    id: 'sentry',
    name: 'Sentry',
    category: 'dev_ops',
    catalogStatus: 'active',
    description: 'Issues, events, and project health from Sentry.',
    icon: 'sentry',
    website: 'https://sentry.io',
    trust: 'verified',
    server: {
      type: 'stdio',
      command: 'npx',
      args: ['-y', '@sentry/mcp-server'],
      package: '@sentry/mcp-server',
    },
    auth: {
      primary: 'api_key_form',
      developer: ['stdio', 'env'],
      fields: [field('SENTRY_AUTH_TOKEN', 'Sentry Auth Token', 'sntrys_...')],
    },
    capabilities: { search: true, read: true, write: true, transact: false },
  },
  {
    id: 'puppeteer',
    name: 'Browser (Puppeteer)',
    category: 'dev_ops',
    catalogStatus: 'active',
    description: 'Controlled browser automation for scraping and testing.',
    icon: 'web',
    trust: 'community',
    server: {
      type: 'stdio',
      command: 'npx',
      args: ['-y', '@modelcontextprotocol/server-puppeteer'],
      package: '@modelcontextprotocol/server-puppeteer',
    },
    auth: { primary: 'none', developer: ['stdio'] },
    capabilities: { search: true, read: true, write: true, transact: false },
    tools: { alwaysConfirm: ['click', 'type', 'navigate', 'screenshot'] },
  },
  {
    id: 'memory',
    name: 'MCP Memory',
    category: 'productivity',
    catalogStatus: 'active',
    description: 'Persistent knowledge graph memory via MCP.',
    icon: 'brain',
    trust: 'verified',
    server: {
      type: 'stdio',
      command: 'npx',
      args: ['-y', '@modelcontextprotocol/server-memory'],
      package: '@modelcontextprotocol/server-memory',
    },
    auth: { primary: 'none', developer: ['stdio'] },
    capabilities: { search: true, read: true, write: true, transact: false },
  },
  {
    id: 'home-assistant',
    name: 'Home Assistant',
    category: 'smart_home',
    catalogStatus: 'active',
    description: 'Control and monitor your smart home via Home Assistant MCP.',
    icon: 'home',
    website: 'https://www.home-assistant.io',
    trust: 'verified',
    server: { type: 'remote' },
    auth: {
      primary: 'remote_url',
      developer: ['remote_url', 'api_key_form', 'oauth'],
      oauth: {
        scopes: ['mcp'],
      },
      fields: [field('HOME_ASSISTANT_TOKEN', 'Long-lived access token', 'eyJ...')],
      connectGuide: [
        { title: 'Instance URL', body: 'Enter your Home Assistant MCP endpoint (e.g. https://your-home.example.com/mcp).' },
        { title: 'API token', body: 'Alternatively paste a long-lived access token in the Developer tab.' },
      ],
    },
    capabilities: { search: true, read: true, write: true, transact: true },
    tools: { alwaysConfirm: ['turn_on', 'turn_off', 'set', 'lock', 'unlock', 'open'] },
  },
  {
    id: 'stripe',
    name: 'Stripe',
    category: 'finance',
    catalogStatus: 'active',
    description: 'Customers, payments, and billing data from Stripe.',
    icon: 'payments',
    website: 'https://stripe.com',
    trust: 'verified',
    server: {
      type: 'stdio',
      command: 'npx',
      args: ['-y', '@stripe/mcp'],
      package: '@stripe/mcp',
    },
    auth: {
      primary: 'api_key_form',
      developer: ['stdio', 'env'],
      fields: [field('STRIPE_SECRET_KEY', 'Stripe Secret Key', 'sk_live_... or sk_test_...')],
      connectGuide: [
        { title: 'Stripe dashboard', body: 'Create a restricted API key in Stripe Dashboard → Developers → API keys.' },
      ],
    },
    capabilities: { search: true, read: true, write: true, transact: true },
    tools: { alwaysConfirm: ['create', 'charge', 'refund', 'pay', 'transfer'] },
  },
  {
    id: 'paypal',
    name: 'PayPal',
    category: 'finance',
    catalogStatus: 'active',
    description: 'PayPal transactions and account operations via MCP.',
    icon: 'payments',
    website: 'https://paypal.com',
    trust: 'verified',
    server: {
      type: 'stdio',
      command: 'npx',
      args: ['-y', '@paypal/mcp'],
      package: '@paypal/mcp',
    },
    auth: {
      primary: 'api_key_form',
      developer: ['stdio', 'env'],
      fields: [
        field('PAYPAL_CLIENT_ID', 'PayPal Client ID', '', false),
        field('PAYPAL_CLIENT_SECRET', 'PayPal Client Secret', ''),
      ],
    },
    capabilities: { search: true, read: true, write: true, transact: true },
    tools: { alwaysConfirm: ['pay', 'transfer', 'send', 'create'] },
  },
  {
    id: 'shopify',
    name: 'Shopify',
    category: 'shopping',
    catalogStatus: 'active',
    description: 'Products, orders, and store data from Shopify.',
    icon: 'store',
    website: 'https://shopify.com',
    trust: 'verified',
    server: {
      type: 'stdio',
      command: 'npx',
      args: ['-y', '@shopify/dev-mcp'],
      package: '@shopify/dev-mcp',
    },
    auth: {
      primary: 'api_key_form',
      developer: ['stdio', 'env'],
      fields: [
        field('SHOPIFY_ACCESS_TOKEN', 'Shopify Admin API access token', 'shpat_...'),
        field('SHOPIFY_STORE_DOMAIN', 'Store domain', 'your-store.myshopify.com', false),
      ],
    },
    capabilities: { search: true, read: true, write: true, transact: true },
    tools: { alwaysConfirm: ['create', 'update', 'delete', 'fulfill', 'refund'] },
  },
];
