import { candidateStdio } from '../helpers.js';

/** Evaluation candidates — shown in the store alongside shipped integrations. */
export const COMMUNICATION_CANDIDATES = [
  candidateStdio({
    id: 'twilio',
    name: 'Twilio',
    category: 'communication',
    pkg: 'twilio-mcp',
    description: 'SMS and voice via Twilio API.',
    icon: 'sms',
    website: 'https://twilio.com',
    envKey: 'TWILIO_AUTH_TOKEN',
    envLabel: 'Twilio Auth Token',
  }),
  candidateStdio({
    id: 'zoom',
    name: 'Zoom',
    category: 'communication',
    pkg: 'zoom-mcp-server',
    description: 'Meetings and calendar from Zoom.',
    icon: 'video',
    website: 'https://zoom.us',
    authPrimary: 'oauth',
  }),
  candidateStdio({
    id: 'zendesk',
    name: 'Zendesk',
    category: 'communication',
    pkg: 'zendesk-mcp',
    description: 'Tickets, users, and help center content.',
    icon: 'support',
    website: 'https://zendesk.com',
    envKey: 'ZENDESK_API_TOKEN',
    envLabel: 'Zendesk API Token',
  }),
  candidateStdio({
    id: 'whatsapp',
    name: 'WhatsApp Business',
    category: 'communication',
    pkg: 'whatsapp-mcp',
    description: 'WhatsApp Business API messaging.',
    icon: 'chat',
    website: 'https://business.whatsapp.com',
    envKey: 'WHATSAPP_ACCESS_TOKEN',
    envLabel: 'WhatsApp Access Token',
    transact: true,
  }),
  candidateStdio({
    id: 'slack',
    name: 'Slack',
    category: 'communication',
    pkg: '@modelcontextprotocol/server-slack',
    description: 'Read channels, search messages, and post updates to Slack.',
    icon: 'slack',
    website: 'https://slack.com',
    envKey: 'SLACK_BOT_TOKEN',
    envLabel: 'Slack Bot Token',
  }),
];
