import type { GeneratedSkill } from './SkillGenerator.js';

/**
 * Pre-bundled skill catalog — 50 ready-to-use skills covering common
 * development, devops, testing, documentation, security, and infrastructure patterns.
 * These seed the SkillGenerator and can be matched to user queries automatically.
 */

export const BUNDLED_SKILLS: GeneratedSkill[] = [
  // ═══ CODE GENERATION ═══
  { id: 'skill-init-react', name: 'Initialize React App', description: 'Scaffold a new React application with Vite or CRA', triggerPatterns: ['create react app', 'new react project', 'scaffold react', 'init react'], prompt: 'Create a new React application using Vite (preferred) or Create React App. Set up the project structure with src/, ensure package.json has proper scripts, install dependencies, and verify the dev server starts.', tools: ['shell_exec', 'file_write', 'file_read'], createdAt: '2026-01-01', usageCount: 0 },
  { id: 'skill-init-next', name: 'Initialize Next.js App', description: 'Scaffold a Next.js project with TypeScript', triggerPatterns: ['create next app', 'next.js project', 'new nextjs', 'init next'], prompt: 'Create a new Next.js application with TypeScript, App Router, and Tailwind CSS. Set up the project, verify the build works, and start the dev server.', tools: ['shell_exec', 'file_write', 'file_read'], createdAt: '2026-01-01', usageCount: 0 },
  { id: 'skill-init-express', name: 'Create Express API', description: 'Scaffold an Express.js backend with TypeScript', triggerPatterns: ['create express api', 'express server', 'node backend', 'rest api'], prompt: 'Create an Express.js server with TypeScript, proper middleware (cors, json-parser, helmet), error handling, and a health endpoint. Include tsconfig.json and npm scripts for dev/build/start.', tools: ['shell_exec', 'file_write', 'folder_create'], createdAt: '2026-01-01', usageCount: 0 },
  { id: 'skill-init-python', name: 'Initialize Python Package', description: 'Scaffold a Python project with virtualenv and setup', triggerPatterns: ['create python package', 'new python project', 'python setup', 'init python'], prompt: 'Create a Python project with virtualenv, setup.py/pyproject.toml, requirements.txt, and proper src/ structure. Include type hints and at least one test.', tools: ['shell_exec', 'file_write', 'folder_create'], createdAt: '2026-01-01', usageCount: 0 },
  { id: 'skill-init-rust', name: 'Initialize Rust Project', description: 'Create a Rust project with cargo', triggerPatterns: ['create rust project', 'new rust', 'cargo init', 'rust setup'], prompt: 'Initialize a Rust project with cargo, set up proper error handling with anyhow/thiserror, add clap for CLI arguments, and ensure the build passes with clippy.', tools: ['shell_exec', 'file_write', 'file_read'], createdAt: '2026-01-01', usageCount: 0 },
  { id: 'skill-init-go', name: 'Initialize Go Module', description: 'Create a Go module with proper structure', triggerPatterns: ['create go project', 'new go module', 'go init', 'go setup'], prompt: 'Initialize a Go module, set up proper package structure (cmd/pkg/internal), add a main.go with a basic server using net/http, and run go mod tidy.', tools: ['shell_exec', 'file_write', 'folder_create'], createdAt: '2026-01-01', usageCount: 0 },

  // ═══ DEVOPS & DEPLOYMENT ═══
  { id: 'skill-dockerize', name: 'Dockerize Application', description: 'Create Dockerfile and compose for an application', triggerPatterns: ['dockerize', 'create dockerfile', 'docker setup', 'containerize'], prompt: 'Create a Dockerfile with multi-stage builds, a .dockerignore file, and a docker-compose.yml. Optimize for layer caching. Verify the container builds.', tools: ['file_write', 'shell_exec', 'file_read'], createdAt: '2026-01-01', usageCount: 0 },
  { id: 'skill-setup-cicd', name: 'Setup CI/CD Pipeline', description: 'Create GitHub Actions workflows', triggerPatterns: ['setup ci', 'ci/cd pipeline', 'github actions', 'deploy pipeline'], prompt: 'Create a GitHub Actions workflow that runs lint, typecheck, tests, and builds on every push/PR. Add caching for node_modules and proper environment variables.', tools: ['file_write', 'folder_create', 'shell_exec'], createdAt: '2026-01-01', usageCount: 0 },
  { id: 'skill-deploy-vercel', name: 'Deploy to Vercel', description: 'Deploy a web app to Vercel', triggerPatterns: ['deploy vercel', 'vercel deploy', 'ship to vercel'], prompt: 'Configure vercel.json, ensure the build command and output directory are correct, deploy using the Vercel CLI, and verify the deployment URL works.', tools: ['shell_exec', 'file_write', 'file_read'], createdAt: '2026-01-01', usageCount: 0 },
  { id: 'skill-setup-monitoring', name: 'Setup Application Monitoring', description: 'Add logging and error tracking to an app', triggerPatterns: ['setup monitoring', 'add logging', 'error tracking', 'observability'], prompt: 'Add structured logging (pino/winston/logrus), error tracking (Sentry/error boundary), and health check endpoints. Configure log levels per environment.', tools: ['file_read', 'code_replace', 'shell_exec'], createdAt: '2026-01-01', usageCount: 0 },
  { id: 'skill-setup-env', name: 'Configure Environment Variables', description: 'Set up .env and environment management', triggerPatterns: ['setup env', 'environment variables', '.env file', 'config management'], prompt: 'Create .env.example with documented variables, add proper validation (zod/env-var), create environment-specific configs, and update .gitignore to exclude .env.', tools: ['file_write', 'file_read', 'code_replace'], createdAt: '2026-01-01', usageCount: 0 },
  { id: 'skill-npm-publish', name: 'Publish NPM Package', description: 'Prepare and publish a package to npm', triggerPatterns: ['publish npm', 'npm publish', 'package publish', 'release package'], prompt: 'Review package.json fields (name, version, main, types, files), update CHANGELOG, bump version, run build+test, then publish to npm with proper tags.', tools: ['file_read', 'shell_exec', 'file_write'], createdAt: '2026-01-01', usageCount: 0 },

  // ═══ TESTING ═══
  { id: 'skill-write-tests', name: 'Write Unit Tests', description: 'Write comprehensive unit tests', triggerPatterns: ['write tests', 'unit tests', 'test coverage', 'add tests'], prompt: 'Write unit tests for the given code. Cover happy paths, edge cases, error states, and async behavior. Use the project testing framework (vitest/jest/pytest). Aim for >80% coverage.', tools: ['file_read', 'file_write', 'code_search', 'test_run'], createdAt: '2026-01-01', usageCount: 0 },
  { id: 'skill-write-integration', name: 'Write Integration Tests', description: 'Write API/integration tests', triggerPatterns: ['integration tests', 'e2e tests', 'api tests', 'end to end'], prompt: 'Write integration tests that test the full stack: API endpoints, database interactions, and service orchestration. Use supertest/httptest. Set up test data and tear down after.', tools: ['file_read', 'file_write', 'code_search', 'test_run'], createdAt: '2026-01-01', usageCount: 0 },
  { id: 'skill-setup-testing', name: 'Setup Test Framework', description: 'Configure a testing framework', triggerPatterns: ['setup testing', 'test framework', 'configure tests', 'test setup'], prompt: 'Install and configure the testing framework (vitest/jest/pytest). Add test scripts to package.json, create test setup files, configure coverage thresholds, and verify a sample test passes.', tools: ['shell_exec', 'file_write', 'file_read'], createdAt: '2026-01-01', usageCount: 0 },
  { id: 'skill-test-coverage', name: 'Improve Test Coverage', description: 'Analyze and increase test coverage', triggerPatterns: ['test coverage', 'improve coverage', 'coverage report'], prompt: 'Run existing tests with coverage, identify uncovered code paths, write additional tests for untested branches, and verify coverage improves above 80% threshold.', tools: ['test_run', 'test_coverage', 'file_read', 'code_search', 'file_write'], createdAt: '2026-01-01', usageCount: 0 },

  // ═══ DOCUMENTATION ═══
  { id: 'skill-gen-readme', name: 'Generate README', description: 'Create a comprehensive README.md', triggerPatterns: ['generate readme', 'create readme', 'write readme', 'documentation'], prompt: 'Generate a README.md with project overview, installation instructions, usage examples, API reference, configuration options, contributing guide, and license section.', tools: ['file_read', 'file_write', 'code_search', 'code_definitions'], createdAt: '2026-01-01', usageCount: 0 },
  { id: 'skill-gen-docs', name: 'Generate API Documentation', description: 'Create API documentation from code', triggerPatterns: ['generate docs', 'api docs', 'document api', 'swagger'], prompt: 'Generate API documentation from the codebase. Include endpoint descriptions, request/response schemas, authentication details, error codes, and usage examples.', tools: ['code_search', 'code_definitions', 'file_read', 'file_write'], createdAt: '2026-01-01', usageCount: 0 },
  { id: 'skill-gen-changelog', name: 'Generate Changelog', description: 'Create a changelog from git history', triggerPatterns: ['generate changelog', 'create changelog', 'release notes'], prompt: 'Read git history since last tag/release, categorize changes (features, fixes, breaking, docs), and generate a CHANGELOG.md in Keep a Changelog format.', tools: ['git_log', 'git_diff', 'file_read', 'file_write'], createdAt: '2026-01-01', usageCount: 0 },
  { id: 'skill-gen-contributing', name: 'Generate Contributing Guide', description: 'Create CONTRIBUTING.md', triggerPatterns: ['contributing guide', 'contributor guide', 'contribute'], prompt: 'Create a CONTRIBUTING.md with development setup, coding standards, pull request process, commit conventions, testing requirements, and code of conduct.', tools: ['file_write', 'file_read'], createdAt: '2026-01-01', usageCount: 0 },

  // ═══ DATABASE ═══
  { id: 'skill-setup-db', name: 'Setup Database', description: 'Configure a database with migrations', triggerPatterns: ['setup database', 'configure db', 'database setup', 'migration'], prompt: 'Set up the database connection, create migration files for the schema, add seed data scripts, and verify the connection works. Use the project ORM or raw SQL.', tools: ['shell_exec', 'file_write', 'file_read', 'db_query'], createdAt: '2026-01-01', usageCount: 0 },
  { id: 'skill-create-migration', name: 'Create Database Migration', description: 'Write a database schema migration', triggerPatterns: ['create migration', 'add migration', 'schema change', 'alter table'], prompt: 'Create a new database migration file. Write the up (apply) and down (rollback) SQL. Include proper indexes, constraints, and comments. Test the migration both directions.', tools: ['file_write', 'db_query', 'shell_exec'], createdAt: '2026-01-01', usageCount: 0 },
  { id: 'skill-seed-db', name: 'Seed Database', description: 'Create seed data for development', triggerPatterns: ['seed database', 'seed data', 'populate db', 'test data'], prompt: 'Create seed data scripts that populate the database with realistic development data. Include users, sample records, and relationships. Make seeds idempotent.', tools: ['file_write', 'db_query', 'file_read'], createdAt: '2026-01-01', usageCount: 0 },
  { id: 'skill-optimize-queries', name: 'Optimize Database Queries', description: 'Find and fix slow queries', triggerPatterns: ['optimize queries', 'slow query', 'query performance', 'db index'], prompt: 'Analyze slow database queries, check for missing indexes, optimize query structure, add EXPLAIN ANALYZE comments, and measure improvement.', tools: ['db_query', 'db_schema', 'code_search', 'code_replace'], createdAt: '2026-01-01', usageCount: 0 },

  // ═══ SECURITY ═══
  { id: 'skill-audit-deps', name: 'Audit Dependencies', description: 'Check for vulnerable dependencies', triggerPatterns: ['audit dependencies', 'security audit', 'check deps', 'vulnerable packages'], prompt: 'Run the package manager audit command (npm audit/pip audit/cargo audit), review findings, update vulnerable packages to patched versions, and verify no breaking changes.', tools: ['shell_exec', 'file_read', 'package_install'], createdAt: '2026-01-01', usageCount: 0 },
  { id: 'skill-scan-secrets', name: 'Scan for Secrets', description: 'Find accidentally committed secrets', triggerPatterns: ['scan secrets', 'find secrets', 'secret scan', 'leaked keys'], prompt: 'Scan the codebase and git history for API keys, tokens, passwords, and other secrets. Use regex patterns and git-secrets tool. Report findings and suggest remediation.', tools: ['shell_exec', 'code_search', 'git_log', 'security_secrets'], createdAt: '2026-01-01', usageCount: 0 },
  { id: 'skill-setup-auth', name: 'Setup Authentication', description: 'Add auth module to application', triggerPatterns: ['setup auth', 'add authentication', 'login system', 'jwt auth'], prompt: 'Implement authentication with bcrypt password hashing, JWT access+refresh tokens, login/register endpoints, and middleware for protected routes. Add rate limiting and session management.', tools: ['file_write', 'code_replace', 'shell_exec', 'file_read'], createdAt: '2026-01-01', usageCount: 0 },
  { id: 'skill-configure-cors', name: 'Configure CORS', description: 'Set up CORS properly', triggerPatterns: ['configure cors', 'cors setup', 'cross origin'], prompt: 'Configure CORS with allowed origins, methods, headers, and credentials. Ensure the configuration is restrictive in production and permissive in development. Test cross-origin requests.', tools: ['file_read', 'code_replace', 'code_search'], createdAt: '2026-01-01', usageCount: 0 },
  { id: 'skill-encrypt-data', name: 'Encrypt Sensitive Data', description: 'Implement data encryption at rest', triggerPatterns: ['encrypt data', 'data encryption', 'encrypt at rest', 'aes encrypt'], prompt: 'Implement AES-256-GCM encryption for sensitive data at rest. Use envelope encryption with key derivation. Add encrypt/decrypt utilities and ensure keys are never logged.', tools: ['file_read', 'file_write', 'code_replace'], createdAt: '2026-01-01', usageCount: 0 },

  // ═══ PERFORMANCE ═══
  { id: 'skill-analyze-bundle', name: 'Analyze Bundle Size', description: 'Find and reduce large bundles', triggerPatterns: ['bundle size', 'analyze bundle', 'reduce bundle', 'webpack bundle'], prompt: 'Run the bundle analyzer, identify large dependencies and chunks, apply code splitting/dynamic imports, remove unused imports, and verify bundle size reduction.', tools: ['shell_exec', 'file_read', 'code_replace'], createdAt: '2026-01-01', usageCount: 0 },
  { id: 'skill-optimize-images', name: 'Optimize Images', description: 'Optimize and compress images', triggerPatterns: ['optimize images', 'compress images', 'image optimization'], prompt: 'Identify large images, convert to modern formats (WebP/AVIF), add responsive sizes, implement lazy loading, and verify quality is maintained.', tools: ['shell_exec', 'file_find', 'image_resize', 'image_convert'], createdAt: '2026-01-01', usageCount: 0 },
  { id: 'skill-add-caching', name: 'Add Caching Layer', description: 'Implement caching for improved performance', triggerPatterns: ['add caching', 'cache layer', 'redis cache', 'response cache'], prompt: 'Add caching for expensive operations: API responses, database queries, computed values. Use in-memory cache for dev and Redis for production. Add cache invalidation strategy.', tools: ['file_read', 'code_replace', 'code_insert', 'file_write'], createdAt: '2026-01-01', usageCount: 0 },
  { id: 'skill-lazy-load', name: 'Implement Lazy Loading', description: 'Add code splitting and lazy loading', triggerPatterns: ['lazy load', 'code splitting', 'dynamic import'], prompt: 'Implement code splitting with React.lazy/dynamic imports. Split routes, large components, and heavy libraries. Verify chunk sizes and loading states.', tools: ['code_search', 'code_replace', 'shell_exec'], createdAt: '2026-01-01', usageCount: 0 },

  // ═══ GIT WORKFLOW ═══
  { id: 'skill-branch-workflow', name: 'Setup Branch Workflow', description: 'Configure git branching strategy', triggerPatterns: ['branch workflow', 'git flow', 'branch strategy', 'git workflow'], prompt: 'Set up the branching strategy (main, develop, feature/*, hotfix/*). Configure branch protection rules, add PR templates, and update the README with the workflow.', tools: ['git_branch', 'file_write', 'shell_exec'], createdAt: '2026-01-01', usageCount: 0 },
  { id: 'skill-precommit-hooks', name: 'Setup Pre-commit Hooks', description: 'Add git hooks for quality checks', triggerPatterns: ['pre-commit', 'git hooks', 'husky', 'lint staged'], prompt: 'Set up pre-commit hooks with husky/lint-staged: run linter, formatter, and type-check on staged files before commit. Add commit message linting with commitlint.', tools: ['shell_exec', 'file_write', 'package_install'], createdAt: '2026-01-01', usageCount: 0 },
  { id: 'skill-resolve-conflicts', name: 'Resolve Merge Conflicts', description: 'Systematically resolve git merge conflicts', triggerPatterns: ['merge conflict', 'resolve conflict', 'git merge', 'rebase conflict'], prompt: 'Identify conflicting files, understand both sides of each conflict, choose the correct resolution or merge both, run tests after resolving, and commit the resolution.', tools: ['git_status', 'git_diff', 'file_read', 'code_replace', 'test_run'], createdAt: '2026-01-01', usageCount: 0 },
  { id: 'skill-git-cleanup', name: 'Clean Git History', description: 'Squash commits and clean up branches', triggerPatterns: ['clean git', 'squash commits', 'clean history', 'delete branch'], prompt: 'Squash WIP commits into logical units, rebase feature branches on main, delete merged branches, and run git gc to optimize the repository.', tools: ['git_log', 'git_branch', 'shell_exec'], createdAt: '2026-01-01', usageCount: 0 },

  // ═══ CODE QUALITY ═══
  { id: 'skill-refactor-code', name: 'Refactor Code', description: 'Systematically refactor with safety', triggerPatterns: ['refactor', 'clean code', 'improve code', 'code quality'], prompt: 'Read and understand the code, identify improvements (DRY, SOLID, patterns), refactor incrementally with tests passing between each change, and verify behavior is preserved.', tools: ['file_read', 'code_search', 'code_replace', 'test_run', 'git_diff'], createdAt: '2026-01-01', usageCount: 0 },
  { id: 'skill-fix-linter', name: 'Fix Linter Errors', description: 'Resolve all linter warnings and errors', triggerPatterns: ['fix lint', 'lint errors', 'eslint', 'prettier'], prompt: 'Read the linter output, fix all errors and warnings, run auto-fix where possible, manually resolve complex issues, and verify the linter passes clean.', tools: ['code_lint', 'code_search', 'code_replace', 'code_format'], createdAt: '2026-01-01', usageCount: 0 },
  { id: 'skill-upgrade-deps', name: 'Upgrade Dependencies', description: 'Update outdated packages safely', triggerPatterns: ['upgrade dependencies', 'update packages', 'outdated deps', 'bump deps'], prompt: 'Check for outdated packages, review changelogs for breaking changes, upgrade one major at a time, run tests after each upgrade, and fix any compatibility issues.', tools: ['package_outdated', 'package_install', 'shell_exec', 'test_run'], createdAt: '2026-01-01', usageCount: 0 },
  { id: 'skill-add-types', name: 'Add TypeScript Types', description: 'Add or improve TypeScript type coverage', triggerPatterns: ['add types', 'type safety', 'typescript types', 'strict mode'], prompt: 'Enable strict TypeScript checks, add proper types to untyped code, eliminate any types where possible, add proper generics and type guards, and fix all type errors.', tools: ['code_search', 'code_replace', 'code_typecheck', 'file_read'], createdAt: '2026-01-01', usageCount: 0 },

  // ═══ DEBUGGING ═══
  { id: 'skill-debug-error', name: 'Debug Application Error', description: 'Systematically debug and fix an error', triggerPatterns: ['debug', 'fix error', 'bug fix', 'troubleshoot'], prompt: 'Reproduce the error, read error logs, trace through code to find root cause, implement a fix, add a regression test, and verify the fix works. Document the fix.', tools: ['file_read', 'code_search', 'shell_exec', 'git_blame', 'test_run'], createdAt: '2026-01-01', usageCount: 0 },
  { id: 'skill-debug-memory', name: 'Debug Memory Issues', description: 'Find and fix memory leaks', triggerPatterns: ['memory leak', 'memory issue', 'heap dump', 'oom'], prompt: 'Take a heap snapshot, identify objects holding excessive memory, find event listener/subscription leaks, add cleanup in useEffect/componentWillUnmount, and verify memory stabilizes.', tools: ['shell_exec', 'code_search', 'code_replace', 'system_monitor'], createdAt: '2026-01-01', usageCount: 0 },
  { id: 'skill-debug-network', name: 'Debug Network Issues', description: 'Troubleshoot API and network problems', triggerPatterns: ['network error', 'api timeout', 'connection issue', 'cors error'], prompt: 'Check network connectivity, verify API endpoints are reachable, inspect request/response headers and bodies, check for CORS/SSL/timeout issues, and implement proper error handling.', tools: ['shell_exec', 'http_get', 'http_request', 'code_search'], createdAt: '2026-01-01', usageCount: 0 },

  // ═══ INFRASTRUCTURE ═══
  { id: 'skill-setup-docker-compose', name: 'Setup Docker Compose', description: 'Create multi-service compose setup', triggerPatterns: ['docker compose', 'compose file', 'multi service', 'service orchestration'], prompt: 'Create a docker-compose.yml with all services (app, db, cache, proxy). Configure networks, volumes, health checks, environment variables, and proper dependency ordering.', tools: ['file_write', 'shell_exec', 'file_read'], createdAt: '2026-01-01', usageCount: 0 },
  { id: 'skill-setup-nginx', name: 'Setup Nginx Reverse Proxy', description: 'Configure Nginx as reverse proxy', triggerPatterns: ['setup nginx', 'nginx config', 'reverse proxy', 'proxy setup'], prompt: 'Create an Nginx configuration for reverse proxy with SSL termination, static file serving, WebSocket support, caching headers, rate limiting, and security headers.', tools: ['file_write', 'shell_exec', 'file_read'], createdAt: '2026-01-01', usageCount: 0 },
  { id: 'skill-backup-restore', name: 'Setup Backup Strategy', description: 'Create database and file backup system', triggerPatterns: ['backup', 'restore', 'backup strategy', 'disaster recovery'], prompt: 'Create backup scripts for database (pg_dump/mongodump) and files. Add scheduling (cron), retention policy, compression, encryption, and a restore verification script.', tools: ['file_write', 'shell_exec', 'db_export'], createdAt: '2026-01-01', usageCount: 0 },
  { id: 'skill-ssl-setup', name: 'Setup SSL/TLS', description: 'Configure HTTPS with Let\'s Encrypt', triggerPatterns: ['setup ssl', 'https', 'lets encrypt', 'ssl certificate'], prompt: 'Set up SSL/TLS certificates using Let\'s Encrypt/certbot. Configure auto-renewal, add HTTP→HTTPS redirect, and set up HSTS headers. Verify SSL Labs score is A+.', tools: ['shell_exec', 'file_write', 'file_read'], createdAt: '2026-01-01', usageCount: 0 },

  // ═══ DATA ═══
  { id: 'skill-process-csv', name: 'Process CSV Data', description: 'Parse and transform CSV files', triggerPatterns: ['process csv', 'csv data', 'parse csv', 'csv transform'], prompt: 'Read a CSV file, parse headers and rows, transform/filter/aggregate the data, and write the results back to a new CSV or JSON file. Handle edge cases and large files.', tools: ['file_read', 'csv_parse', 'json_parse', 'file_write'], createdAt: '2026-01-01', usageCount: 0 },
  { id: 'skill-generate-report', name: 'Generate Report', description: 'Create a data analysis report', triggerPatterns: ['generate report', 'data report', 'analysis report', 'summary report'], prompt: 'Analyze the data, compute key metrics and trends, create visualizations, and generate a comprehensive PDF/Markdown report with executive summary, findings, and recommendations.', tools: ['file_read', 'shell_exec', 'chart_generate', 'pdf_create', 'file_write'], createdAt: '2026-01-01', usageCount: 0 },

  // ═══ PROJECT MANAGEMENT ═══
  { id: 'skill-project-init', name: 'Initialize Project', description: 'Set up a new project from scratch', triggerPatterns: ['init project', 'new project setup', 'start project', 'project scaffold'], prompt: 'Initialize a new project: choose the right tech stack, set up the repository structure, create config files, add README, set up linters/formatters, and make the first commit.', tools: ['shell_exec', 'file_write', 'folder_create', 'git_init', 'git_commit'], createdAt: '2026-01-01', usageCount: 0 },
  { id: 'skill-code-review-prep', name: 'Prepare Code for Review', description: 'Review code before creating a PR', triggerPatterns: ['code review', 'review code', 'prep pr', 'pull request'], prompt: 'Review the diff, check for consistency with project patterns, verify tests pass, ensure documentation is updated, clean up debug code, and prepare a clear PR description.', tools: ['git_diff', 'git_status', 'code_lint', 'test_run', 'file_read'], createdAt: '2026-01-01', usageCount: 0 },
  { id: 'skill-monorepo-setup', name: 'Setup Monorepo', description: 'Configure a monorepo with workspaces', triggerPatterns: ['setup monorepo', 'monorepo', 'workspaces', 'turborepo'], prompt: 'Configure a monorepo with pnpm/npm workspaces or Turborepo. Set up shared configs, interdependency management, parallel builds, and proper CI caching across packages.', tools: ['shell_exec', 'file_write', 'file_read'], createdAt: '2026-01-01', usageCount: 0 },
];

export function getBundledSkills(): GeneratedSkill[] {
  return [...BUNDLED_SKILLS];
}

export function findBundledSkill(query: string): GeneratedSkill | null {
  const lower = query.toLowerCase();
  let best: GeneratedSkill | null = null;
  let bestScore = 0;

  for (const skill of BUNDLED_SKILLS) {
    for (const pattern of skill.triggerPatterns) {
      const score = computeSimilarity(lower, pattern.toLowerCase());
      if (score > bestScore && score > 0.3) {
        bestScore = score;
        best = skill;
      }
    }
  }

  return best;
}

function computeSimilarity(a: string, b: string): number {
  const wordsA = new Set(a.split(/\s+/).filter((w) => w.length > 2));
  const wordsB = new Set(b.split(/\s+/).filter((w) => w.length > 2));
  if (wordsA.size === 0 || wordsB.size === 0) return 0;
  let matches = 0;
  for (const w of wordsA) {
    if (wordsB.has(w)) { matches++; continue; }
    for (const wb of wordsB) {
      if (wb.includes(w) || w.includes(wb)) { matches += 0.5; break; }
    }
  }
  return matches / Math.max(wordsA.size, wordsB.size);
}
